# Generated by Django 5.2.3 on 2026-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance')], default='Romance', max_length=50)),
                ('page', models.IntegerField()),
                ('published', models.DateField()),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['published'],
            },
        ),
    ]
