# Generated by Django 5.2.3 on 2026-04-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Biography', 'Biography'), ('History', 'History'), ('Fiction', 'Fiction'), ('Computers', 'Computers'), ('Science', 'Science')], default='Fiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
