# Generated by Django 5.2.3 on 2026-04-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summarize', models.CharField(blank=True, max_length=500, null=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='reading.reading')),
            ],
            options={
                'db_table': 'ReadingProgress',
                'ordering': ['page_number'],
            },
        ),
    ]
